// <auto-generated />
using Biblioteca_MVC.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Biblioteca_MVC.DAL.migrations
{
    [DbContext(typeof(Biblioteca_MVCContext))]
    [Migration("20230613220149_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Biblioteca_MVC.Models.Biblioteca", b =>
                {
                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SaldoTotal")
                        .HasColumnType("float");

                    b.Property<int>("VentasRealizadas")
                        .HasColumnType("int");

                    b.ToTable("Biblioteca");
                });

            modelBuilder.Entity("Biblioteca_MVC.Models.Libro", b =>
                {
                    b.Property<bool>("Alquilado")
                        .HasColumnType("bit");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CantPaginas")
                        .HasColumnType("int");

                    b.Property<int>("FechaDevolucionEnDias")
                        .HasColumnType("int");

                    b.Property<int>("ISBN")
                        .HasColumnType("int");

                    b.Property<double>("PrecioAlquiler")
                        .HasColumnType("float");

                    b.Property<double>("PrecioCompra")
                        .HasColumnType("float");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Libros");
                });
#pragma warning restore 612, 618
        }
    }
}
